### ISSUE TITLE
Как необходимо подключить к проекту?

### ISSUE THREAD

**Issue by SergeyOleynich** [VKCOM/vk-ios-sdk#146]
Подскажите плиз как правильно подключить к проекту данную библиотеку? Что необходимо скопировать? папку sdk с файлами h и m? И потом еще подключить саму библиотеку VKSdkResources.bundle?В исходной папке с проектом не могу найти libVKSdk.a

**Comment by Tristamoff** [comment]
А у меня вот такая вот проблема /Users/....../VKsdk/Source/VKActivity.m:38:9: No visible @interface for 'UIDevice' declares the selector 'systemVersion'
http://picture-host.ru/pic_b/a9d25c292151e031cceeceb7f2d7f758.png

Причем проявляется только если в эмуляторе выбрано устройство 5S, 6 или 6 Plus. 
На 4, 4S и 5 - работает корректно.

**Comment by moonvader** [comment]
**Получаю** "Command failed due to signal: Segmentation fault: 11"

Что делал - подключал вручную: 
1) перетащил VK-ios-sdk.xcodeproj в проект Xcode 
2) перетащил VKSdkResources.bundle в проект
3) папку Library положил возле VK-ios-sdk.xcodeproj
4) в linked frameworks добавил libVKSdk.a 
5) в brig-header добавил #import "......../VKSdk.h" 
6) в target dependencies своего проекта добавил VKSdk
7) в copy bundle resources добавил VKSdkResources.bundle 

что еще нужно сделать?
p.s. риторический вопрос - что мешало сделать подробную пошаговую инструкцию
