### ISSUE TITLE
Any plans to enable bitcode in sdk?

### ISSUE THREAD

**Issue by doochik** [VKCOM/vk-ios-sdk#315]
I've got the following error when archive my app
```
ld: bitcode bundle could not be generated because '......./VKSdk.framework/VKSdk(VKBundle.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
```

**Comment by dimanicholson** [comment]
I have the same problem.

**Comment by Dreddik** [comment]
I don't know, what is the problem, but bitcode enabled for all of the targets

**Comment by Dreddik** [comment]
Try the latest version please.

**Comment by dimanicholson** [comment]
Верю, что он энэйблед. Но линкер пишет, что bitcode bundle could not be generated because '.../VKSdk.framework/VKSdk(VKSdk.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64. То же самое для armv7.
![screen shot 2015-11-17 at 13 32 58](https://cloud.githubusercontent.com/assets/15811407/11209316/64661dcc-8d31-11e5-931e-6a93cde1614a.png)

**Comment by doochik** [comment]
Да, та же ошибка в 1.3.7

**Comment by Dreddik** [comment]
Framework removed, build from source, or use cocoapods or carthage
