### ISSUE TITLE
Force OAuth in SDK 1.3.7+

### ISSUE THREAD

**Issue by DMAPro** [VKCOM/vk-ios-sdk#322]
Hallo!

Is there a way to force OAuth in the new API? My app checks if VkApp exists on the device, and if it exists, the app shows two options to the user: login via VkApp, or login via OAuth (via Safari). Many users prefer the latter.
A common use case is the following: a user logs in under a fake account, checks that my app doesn't replace all his/her wall's content with links to my app (probably), logs out and logs in via VkApp under his/her main account.
Previously I used `[VKSdk authorize: revokeAccess: forceOAuth:];`. Is there a way to force OAuth authorization in the new API? I couldn't find it. If not, could you please implement it or explain why you removed it?
For now I use 1.2.2.

Also, using [semantic versioning](http://semver.org) would be very convenient, I think.

P.S. Если хотите, можно по-русски, это я просто для наших иностранных товарищей, вдруг кому-то полезно будет :)

**Comment by iwheelbuy** [comment]
Я не разработчик. Но хотелось бы поделиться своим опытом.
Мне раньше тоже нравилось, когда авторизация происходила через Safari (если VK App не установлено).
Однако это причина для того, чтобы ваше приложение отклонили при проверке. Если до сих пор не отклоняли, то это не значит, что никогда больше не отклонят. Зачем рисковать?
Возможно по этой причине был вырезан функционал из vk-ios-sdk.

Вот с такими словами одно из моих приложений было отклонено:

*10.6 Details
We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience. 
Please revise your app to enable users to sign in or register an account in the app. 
We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.*

**Comment by DMAPro** [comment]
@iwheelbuy, спасибо за то, что поделились опытом. Это действительно стоит иметь в виду. Насколько я понимаю, AppStore Review Team в данном случае не устроило, что пользователя перекидывает в Safari вместо использования Web View (Safari View Controller). В таком случае, было бы здорово, чтобы была возможность использовать force OAuth, но вместо открытия ссылки в Safari открывать в Safari View Controller (если он доступен, т.к. AppStore Review Team всё равно тестирует только на последней iOS). Это уже более трудоёмко, конечно. Но тогда хотелось бы знать, есть ли в принципе планы по возвращению данной функциональности.

**Comment by Dreddik** [comment]
Возвращено не будет
